---
# create new group, appservers, and install java
- hosts: web  # Host or Group of Selections
  gather_facts: true
  become: true
  vars:
    httpd_port: 8080
  tasks: 

  - yum:
      pkg: httpd
      state: installed
    when: ansible_distribution == "RedHat"

  - yum:
      pkg: httpd
      state: installed
    when: ansible_distribution == "CentOS"

  - name: Start httpd
    service: name=httpd state=started enabled=yes

- hosts: db # Host or Group of Selections
  tasks:
  - name: Install Mysql web server # Naming the task for debug purpose
    yum: pkg=mysql state=installed  # Using module ( doing the task )
  

- hosts: app
  become: true
  tasks:
  - name: "Install Java and Jenkins"
  yum:
      name: "{{ item.value.name }}"
  loop:
      "{{ lookup('dict',softwares) }}"
  - name: "Starting jenkins"
    service:
        name: "jenkins"
        state: started
        enabled: yes